# @format

name: GitHub Classroom Workflow

on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: install pkg
        run: |
          npm install yarn -g
          yarn install
      - name: create env file
        run: |
          echo AUTH_TOKEN=${{ secrets.AUTH_TOKEN }} >> .env
          echo SESSION_TOKEN=${{ secrets.SESSION_TOKEN }} >> .env
      - name: update classroom data
        run: yarn setup
      - name: build pages
        run: yarn build
      - name: save data files
        run: |
          git config user.name Faith
          git config user.email seventanyb@gmail.com
          git add .
          git commit -am "updata"
          git push origin main
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
